language: go
dist: xenial
go:
  - 1.11.x

branches:
  except:
    - gh-pages

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.3/hugo_extended_0.55.3_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

before_script:
  - rm -rf public 2> /dev/null

script:
  - hugo
  - echo "nmtsn.me" > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
