language: go
go:
  - master
branches:
  except:
    - gh-pages
install:
  - go get github.com/gohugoio/hugo

before_script:
  - rm -rf public 2> /dev/null

script:
  - hugo
  - echo "nmtsn.me" > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
