language: node_js
node_js:
  - "node"
install:
  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
  - npm ci
branches:
  except:
    - gh-pages
stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run test:unit
    - stage: build
      script:
        - npm run build
        - echo nmtsn.me > dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
  local_dir: dist
  target_branch: gh-pages
