language: go
go:
  - 1.11.x

env:
  global:
    - HUGO_BUILD_TAGS="extended"

branches:
  except:
    - gh-pages

before_install:
  - sudo apt-get update
  - sudo apt-get install hugo

before_script:
  - rm -rf public 2> /dev/null

script:
  - hugo
  - echo "nmtsn.me" > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
